const fs=require('fs');
const path=require('path');
const {chromium}=require('playwright');
(async()=>{
  const launch={headless:true};
  if(process.env.INCIDENT_CHROMIUM_PATH){launch.executablePath=process.env.INCIDENT_CHROMIUM_PATH;launch.args=['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage'];}
  const browser=await chromium.launch(launch);
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let html=fs.readFileSync(path.join(__dirname,'../examples/restart-recovery.html'),'utf8');
  if(process.env.INCIDENT_TEST_FONT){const font=fs.readFileSync(process.env.INCIDENT_TEST_FONT).toString('base64');html='<style>@font-face{font-family:TestKR;src:url(data:font/woff2;base64,'+font+')}#eir-report,#eir-report *{font-family:TestKR,system-ui!important}</style>'+html;}
  await page.setContent(html);await page.locator('#eir-title').waitFor();await page.evaluate(()=>document.fonts.ready);
  for(const width of [1024,390,320]){
    await page.setViewportSize({width,height:1000});
    const chart=page.locator('#eir-timeline');await chart.scrollIntoViewIfNeeded();const chartBox=await chart.boundingBox();
    const hitBox=await page.locator('[data-chart-hit]').boundingBox();
    const hoverX=hitBox.x+hitBox.width*.5,hoverY=hitBox.y+hitBox.height*.5;
    await page.mouse.move(hoverX,hoverY);
    await page.locator('#eir-charttip').waitFor({state:'visible'});
    const series=await page.locator('[data-series]').evaluateAll(nodes=>nodes.map(n=>({stroke:n.getAttribute('stroke'),dash:n.getAttribute('stroke-dasharray')})));
    if(series.length!==3||new Set(series.map(n=>n.stroke)).size!==3||new Set(series.map(n=>n.dash)).size!==3)throw Error('series not visually distinguished');
    if(!(await page.locator('#eir-charttip').innerText()).includes('QPS')||!(await page.locator('#eir-charttip').innerText()).includes('표본 시각'))throw Error('tooltip values and actual times');
    const explanation=await page.locator('#eir-charttip [data-metric]').evaluateAll(nodes=>nodes.map(n=>n.innerText));
    if(explanation.length!==3||!explanation[2].includes('p99'))throw Error('all series descriptions');
    const guide=await page.locator('[data-hover-time]').getAttribute('x1');
    if(Math.abs(Number(guide)-(hoverX-chartBox.x))>1)throw Error('hover guide snapped to a sample');
    const normalized=await page.locator('[data-observation]').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('cy'))));
    if(normalized.some(y=>y<40||y>chartBox.height-30))throw Error('series escaped shared plot');
    await page.mouse.click(hoverX,hoverY);await page.mouse.move(1,1);
    if(!(await page.locator('#eir-charttip').isVisible()))throw Error('tooltip pin lost');
    await page.keyboard.press('Escape');
    if(await page.locator('#eir-charttip').isVisible())throw Error('tooltip pin not dismissible');
    await page.locator('#eir-charttime').evaluate(el=>{el.value='280';el.dispatchEvent(new Event('input',{bubbles:true}))});
    if(!(await page.locator('#eir-charttip [data-metric="M3"]').innerText()).includes('관측 없음'))throw Error('hover interpolated missing latency');
    await page.locator('#eir-charttime').evaluate(el=>{el.value='480';el.dispatchEvent(new Event('input',{bubbles:true}))});
    if(!(await page.locator('#eir-charttip').innerText()).includes('1,850 QPS')||!(await page.locator('#eir-charttip').innerText()).includes('2,800 ms'))throw Error('tooltip changed raw units');
    const tipBounds=await page.locator('#eir-charttip').boundingBox();
    if(tipBounds.x<0||tipBounds.x+tipBounds.width>width+1)throw Error('tooltip overflow');
    if(process.env.INCIDENT_SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.INCIDENT_SCREENSHOT_DIR,'report-hover-'+width+'.png'),fullPage:true});
    await page.locator('#eir-charttime').focus();await page.keyboard.press('ArrowRight');
    if((await page.locator('#eir-charttime').inputValue())!=='481')throw Error('keyboard time exploration');
    await page.keyboard.press('Escape');
    await page.locator('[data-view="cause"]').click();
    await page.locator('[data-event="V4"]').click();
    if(!(await page.locator('#eir-eventdetail').innerText()).includes('재부팅'))throw Error('event selection');
    const line=await page.locator('[data-selected-time]').getAttribute('data-selected-time');
    if(Number(line)!==Date.parse('2026-10-08T21:05:00+09:00'))throw Error('time alignment');
    await page.locator('[data-event="V1"]').click();
    if(!(await page.locator('#eir-eventdetail .eir-values').innerText()).includes('관측 없음'))throw Error('missing metric treated as value');
    await page.locator('[data-node="N4"]').click();
    if(!(await page.locator('#eir-cause-detail').innerText()).includes('동시 실행 수'))throw Error('node selection');
    await page.locator('#eir-cause-detail .eir-evidencepicker button').filter({hasText:'E08'}).click();
    if(!(await page.locator('#eir-cause-detail').innerText()).includes('2740'))throw Error('evidence selection');
    await page.locator('[data-edge="C2"]').click();
    if(!(await page.locator('#eir-cause-detail').innerText()).includes('16,000'))throw Error('edge limitation');
    await page.locator('[data-view="investigation"]').click();
    await page.locator('[data-step="I3"]').click();
    if(!(await page.locator('#eir-step-detail').innerText()).includes('동시 실행 수'))throw Error('investigation');
    await page.locator('[data-view="actions"]').click();
    if(!(await page.locator('#eir-unknownlist').innerText()).includes('보상 누락'))throw Error('unknown questions');
    await page.locator('[data-view="cause"]').click();
    const bounds=await page.locator('#eir-report').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth,body:document.body.scrollWidth,win:innerWidth}));
    if(bounds.scroll>bounds.width+1||bounds.body>bounds.win+1)throw Error('horizontal overflow '+JSON.stringify(bounds));
    const d=await page.locator('#eir-data').textContent();
    if(!JSON.parse(d).metrics[2].points.some(p=>p[1]===null))throw Error('null lost');
    if(process.env.INCIDENT_SCREENSHOT_DIR){await page.screenshot({path:path.join(process.env.INCIDENT_SCREENSHOT_DIR,'report-'+width+'.png'),fullPage:true});}
    console.log('PASS width='+width);
  }
  await page.emulateMedia({colorScheme:'dark'});await page.setViewportSize({width:1024,height:1000});
  if(process.env.INCIDENT_SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.INCIDENT_SCREENSHOT_DIR,'report-dark.png'),fullPage:true});
  await page.emulateMedia({media:'print'});
  if(!(await page.locator('#eir-print-document-info').isVisible()) || !(await page.locator('#eir-print-document-info').innerText()).includes('Asia/Seoul'))throw Error('print document metadata missing');
  await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));
  if(!(await page.locator('#eir-print-evidence details').first().getAttribute('open')===''))throw Error('print evidence not expanded');
  await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
  const touchContext=await browser.newContext({viewport:{width:390,height:900},isMobile:true,hasTouch:true});
  const touchPage=await touchContext.newPage();touchPage.on('pageerror',e=>errors.push(e.message));await touchPage.setContent(html);
  await touchPage.locator('[data-chart-hit]').tap();
  if(!(await touchPage.locator('#eir-charttip').innerText()).includes('시각 고정'))throw Error('touch tooltip pin');
  const touchBounds=await touchPage.locator('#eir-charttip').boundingBox();
  if(!touchBounds||touchBounds.x<0||touchBounds.x+touchBounds.width>390)throw Error('touch tooltip layout');
  await touchPage.locator('[data-chart-hit]').tap();
  if(await touchPage.locator('#eir-charttip').isVisible())throw Error('touch tooltip unpin');
  if(errors.length)throw Error(errors.join(';'));
  console.log('PASS overlaid series, hover values/descriptions, exact cursor, pin, keyboard, null gaps, evidence, responsive layout and print.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
